### ISSUE TITLE
Failed to seed the subdivisions table - v1.0.1

### ISSUE THREAD

**Issue by mishijima** [sidm/laravel-subdivisions#1]
Hi,

First of all, thanks for your great work.

The 'country' column in the subdivisions table is set to 2 chars, while the 'country' value in item no 1833 in subdivisions.json has 3 chars. Hence, the seeding will fail.

Do you even need item no. 1833? Also, I have a feeling the last two items (4386, 4387) in subdivisions.json might not be needed?

```
    "1833": {
        "country": "ISO",
        "country_name": "Country",
        "iso_3166_2": "ISO2",
        "region": "Region",
        "region_alt": "AltName1"
    }
```

Thanks again

**Comment by sidm** [comment]
The latest update has those entries removed, you are correct that they are not needed! This should fix the issues you were having. Let me know if you have any other issues, and I'll be happy to take a look. Sorry for the delay in replying, and I'm so glad you found this useful! Best of luck!

**Comment by mishijima** [comment]
Thanks heaps!
